conda-forge/occt-feedstock

.appveyor.yml
.ci_support/linux_.yaml
.ci_support/osx_.yaml
.ci_support/win_.yaml
.circleci/build_steps.sh
.circleci/fast_finish_ci_pr_build.sh
.circleci/run_docker_build.sh
.circleci/run_osx_build.sh
.github/PULL_REQUEST_TEMPLATE.md
README.md
recipe/bld.bat
recipe/meta.yaml

Checklist
* [x ] Used a fork of the feedstock to propose changes
* [x ] Bumped the build number (if the version is unchanged)
* [x ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`

update to newer deps and pin tbb

---

.azure-pipelines/build_steps.sh
README.md
recipe/boolean_intersection.patch
recipe/meta.yaml

Patch boolean intersection

---

.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.gitattributes
README.md
recipe/bld.bat
recipe/build.sh
recipe/fix-private-linking.patch
recipe/meta.yaml
recipe/no-xmu.patch

Diff from dlr sc

---

.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
recipe/fix-brepblend.patch
recipe/meta.yaml

add patch from DLR-SC

---

recipe/bld.bat
recipe/build.sh
recipe/cmake_policy.patch
recipe/meta.yaml
recipe/vtk.patch

VTK support

---

recipe/bld.bat
recipe/build.sh
recipe/meta.yaml

Add freeimage

---

recipe/bld.bat
recipe/build.sh
recipe/meta.yaml

Add rapidjson to dependencies and enable GLTF support

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
.scripts/run_docker_build.sh
recipe/meta.yaml

Move to 7.5.1

---

recipe/error-checking.patch
recipe/meta.yaml

add error-checking patch

---

.azure-pipelines/azure-pipelines-osx.yml
.ci_support/osx_arm64_.yaml
.scripts/build_steps.sh
.scripts/logging_utils.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
README.md
conda-forge.yml
recipe/meta.yaml

add osx_arm64 support

---

recipe/fix-step-import.patch
recipe/meta.yaml

See issue reported in realthunder/FreeCAD_Assembly3#865

Add fix-step-import.patch

---

.ci_support/linux_64_.yaml
.ci_support/linux_ppc64le_.yaml
.ci_support/osx_64_.yaml
.ci_support/win_64_.yaml
recipe/meta.yaml

Build 7.5.3

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/linux_ppc64le_.yaml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
LICENSE.txt
recipe/meta.yaml

Update to 7.6.1

---

recipe/bld.bat
recipe/build.sh
recipe/meta.yaml

disable exceptions

---

.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/migrations/vtk903.yaml
.ci_support/migrations/vtk910.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.ci_support/win_64_.yaml
.circleci/config.yml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
LICENSE.txt
build-locally.py
recipe/meta.yaml

Update for 7.6.3

---

.azure-pipelines/azure-pipelines-win.yml
.circleci/config.yml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
README.md
recipe/meta.yaml
recipe/patches/blobfish.patch

feat: update to 7.7.0

---

recipe/meta.yaml

Checklist
Not sure what happened that sha changed, but I also confirmed it locally.

fix: update 7.7.0 sha

---

.azure-pipelines/azure-pipelines-win.yml
.ci_support/migrations/vtk925.yaml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
README.md
recipe/meta.yaml

update to 7.7.1

---

README.md
recipe/meta.yaml
recipe/patches/blobfish.patch

Reverts conda-forge/occt-feedstock#102
wrongly merged into main instead of separate 7.6 branch

Revert "7.6.3"

---

recipe/meta.yaml

update to occt-772

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/migrations/vtk926.yaml
.ci_support/osx_64_variantall.yaml
.ci_support/osx_64_variantnovtk.yaml
.ci_support/osx_arm64_variantall.yaml
.ci_support/osx_arm64_variantnovtk.yaml
.gitignore
.scripts/build_steps.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
README.md
recipe/meta.yaml
recipe/patches/blobfish.patch

Checklist
Side note: I've removed 2 diffs from `blobfish.patch` that has been already applied in the upstream.

feat: update to 7.8.0

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_variantall.yaml
.ci_support/linux_64_variantnovtk.yaml
.ci_support/linux_aarch64_variantall.yaml
.ci_support/linux_aarch64_variantnovtk.yaml
.ci_support/linux_ppc64le_variantall.yaml
.ci_support/linux_ppc64le_variantnovtk.yaml
.ci_support/osx_64_variantall.yaml
.ci_support/osx_64_variantnovtk.yaml
.ci_support/osx_arm64_variantall.yaml
.ci_support/osx_arm64_variantnovtk.yaml
.ci_support/win_64_variantall.yaml
.ci_support/win_64_variantnovtk.yaml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
azure-pipelines.yml
build-locally.py
recipe/meta.yaml

feat: update to 7.8.1
